### PR TITLE
[24_6] generate static page for devel dir

### PR DESCRIPTION
**Pull request by Charonxin**
## Why you open this Pull Request?

as title, ref: https://github.com/XmacsLabs/lolly/blob/main/.github/workflows/ci-doxygen.yml

## What work have you done in the current Pull Request?

- [x] generate tm files in devel/ into static page

### CODE REVIEW

**Comment by Charonxin** [comment]
we may support an index.html for main page

**Comment by darcy-shen** [comment]
We can publish tm2html command line to the next beta release, and use it in this CI.

**Comment by Charonxin** [comment]
> We can publish tm2html command line to the next beta release, and use it in this CI.

ok

**Comment by darcy-shen** [comment]
Created a project for you: https://github.com/XmacsLabs/mogan/pull/1094

First of all, you can reduce the size of libmogan.

**Pull request closed without merging**
